version: '3.8'

services:
  # PostgreSQL Database
  fxdeals-db:
    image: postgres:15-alpine
    container_name: fxdeals-postgres
    environment:
      POSTGRES_DB: fxdeals_db
      POSTGRES_USER: fxdeals_user
      POSTGRES_PASSWORD: fxdeals_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - fxdeals-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fxdeals_user -d fxdeals_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # FX Deals Application
  fxdeals-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fxdeals-application
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://fxdeals-db:5432/fxdeals_db
      SPRING_DATASOURCE_USERNAME: fxdeals_user
      SPRING_DATASOURCE_PASSWORD: fxdeals_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      LOGGING_LEVEL_COM_PROGRESSOFT_FXDEALS: INFO
    ports:
      - "8080:8080"
    depends_on:
      fxdeals-db:
        condition: service_healthy
    networks:
      - fxdeals-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/fxdeals/api/deals/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fxdeals-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fxdeals.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - fxdeals-db
    networks:
      - fxdeals-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

networks:
  fxdeals-network:
    driver: bridge
    name: fxdeals-network

volumes:
  postgres_data:
    name: fxdeals-postgres-data
  pgadmin_data:
    name: fxdeals-pgadmin-data
  app_logs:
    name: fxdeals-app-logs 